cmake \
  -DENABLE_SOLVER_STP=ON \
  -DENABLE_POSIX_RUNTIME=ON \
  -DENABLE_KLEE_UCLIBC=ON \
  -DKLEE_UCLIBC_PATH=/PATH/TO/UCLIBC/ \
  -DLLVM_CONFIG_BINARY=/usr/bin/llvm-config \
  -DLLVMCC=/usr/bin/clang \
  -DLLVMCXX=/usr/bin/clang++\
  -DCMAKE_BUILD_TYPE=Release \
  /PATH/TO/SOURCE/
